# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3.3'

services:
  mysql-savz:
    image: mysql:latest
    restart: always
    container_name: mysql-docker
    environment:
      - MYSQL_DATABASE=UserAuthDB
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=root
      # You can use whatever password you like
      - MYSQL_PASSWORD=root
      # Password for root access
      - MYSQL_ROOT_PASSWORD=root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      
  user-authentication:
    image: user-auth-service
    build: UserAuthentication/
    restart: always
    links:
      - mysql-savz
    container_name: user-auth-service-docker
    environment:
      - DATABASE_HOST=mysql-docker
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=UserAuthDB
      - DATABASE_PORT=3306
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on: 
      - mysql-savz
    
  